Tekst/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('routing.urls')),
    path('post/', include('posts.urls')),
    path('space/', include('spaces.urls')),
    path('authentication/', include('authentication.urls')),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

api/urls.py
from django.urls import path
from django.urls import include
from .views import (SpaceDetailView, SpaceListView, TagListView, FollowSpaceView, UnfollowSpaceView, SpacePostsView,
                    CreateCommentView, CommentListView, LikeCommentView, DislikeCommentView, CreateReactionView,
                    DeleteReactionView, DeleteCommentView, UpdateCommentView, PostListView, CommentGetView,
                    PostSaveView, PostSavedRemoveView, FollowUserView, UnfollowUserView, ProfileVisibilityUpdateView,
                    update_profile_view, DeletePostView, DeleteSpaceView, ReportUserView)

urlpatterns = [
    path('space/', include([
        path('all/', SpaceListView.as_view(), name='get_all_spaces'),
        path('<int:pk>/', SpaceDetailView.as_view(), name='get_space_details'),
        path('<int:pk>/delete/', DeleteSpaceView.as_view(), name='delete_space'),
        path('<int:pk>/posts/', SpacePostsView.as_view(), name='get_space_posts'),
        path('follow/<int:pk>/', FollowSpaceView.as_view(), name='follow_space'),
        path('unfollow/<int:pk>/', UnfollowSpaceView.as_view(), name='unfollow_space')
    ])),
    path('tags/', include([
        path('all/', TagListView.as_view(), name='get_all_tags')
    ])),
    path('comment/', include([
        path('get/<int:pk>/', CommentGetView.as_view(), name='get_comment'),
        path('create/', CreateCommentView.as_view(), name='create_comment'),
        path('<int:post_pk>/', CommentListView.as_view(), name='get_post_comments'),
        path('<int:pk>/like/', LikeCommentView.as_view(), name='like_comment'),
        path('<int:pk>/dislike/', DislikeCommentView.as_view(), name='dislike_comment'),
        path('<int:pk>/delete/', DeleteCommentView.as_view(), name='delete_comment'),
        path('<int:pk>/update/', UpdateCommentView.as_view(), name='update_comment')
    ])),
    path('reaction/', include([
        path('create/', CreateReactionView.as_view(), name='create_reaction'),
        path('delete/', DeleteReactionView.as_view(), name="delete_reaction")
    ])),
    path('post/', include([
        path('<int:pk>/delete/', DeletePostView.as_view(), name='delete_post'),
        path('save/', PostSaveView.as_view(), name='save_post'),
        path('<int:pk>/remove-saved/', PostSavedRemoveView.as_view(), name='remove_saved_post'),
        path('all/', PostListView.as_view(), name='get_all_posts'),
    ])),
    path('user/', include([
        path('follow/', FollowUserView.as_view(), name='follow_user'),
        path('unfollow/', UnfollowUserView.as_view(), name='unfollow_user'),
        path('report/', ReportUserView.as_view(), name='report_user'),
    ])),
    path('profile/', include([
        path('<int:pk>/visibility/', ProfileVisibilityUpdateView.as_view(), name='update_profile_visibility'),
        path('update/', update_profile_view, name='update_profile')
    ]))
]

routing/urls.py
from django.urls import path, include
from routing.views import Home, UserProfile, UserInfoEdit, UserFollowersAndFollowing, search
from notifications.views import UserListNotifications

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('search/', search, name='search'),
    path('user/', include([
        path('edit/', UserInfoEdit.as_view(), name='user_edit'),
        path('profile/<slug:slug>/', UserProfile.as_view(), name='user_profile'),
        path('ffs/<slug:slug>/', UserFollowersAndFollowing.as_view(), name='user_ffs'),
        path('notifications/', UserListNotifications.as_view(), name='user_notifications')
    ]))
]

notifications/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Notification(models.Model):
    NOTIFICATION_TYPE_CHOICES = [
        ('follow', 'Следване'),
        ('reply', 'Отговор'),
        ('post_created', 'Публикация създадена'),
        ('post_deleted', 'Публикация изтрита'),
        ('space_created', 'Тема създадена'),
        ('space_deleted', 'Тема изтрита'),
    ]

    notification_type = models.CharField(
        max_length=20,
        choices=NOTIFICATION_TYPE_CHOICES,
    )

    is_read = models.BooleanField(default=False)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    extra_data = models.JSONField(null=True, blank=True)

routing/models.py
from django.db import models

# Create your models here.

notifications/views.py
from django.views.generic.list import ListView
from .models import Notification


class UserListNotifications(ListView):
    model = Notification
    template_name = 'user/notifications.html'
    context_object_name = 'notifications'

    def get_queryset(self, *args, **kwargs):
        queryset = super(UserListNotifications, self).get_queryset()
        queryset = queryset.filter(user=self.request.user).order_by('-timestamp')
        queryset.filter(is_read=False).update(is_read=True)
        return queryset

routing/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic.base import TemplateView
from posts.models import Post, Comment
from spaces.models import Space
from authentication.models import Profile, UserFollows, UserReport
from spaces.models import Space
from django.db.models import Q
from django.contrib.auth import get_user_model

User = get_user_model()


class Home(TemplateView):
    template_name = 'index.html'


def search(request):
    q = request.GET.get('q')

    if q:
        posts = Post.objects.filter(
            (Q(name__icontains=q) | Q(content__icontains=q)) & Q(visibility=True)
        )[:30]
        spaces = Space.objects.filter(
            Q(name__icontains=q) | Q(description__icontains=q)
        )[:30]
        users = User.objects.filter(
            Q(username__icontains=q)
        )[:30]
    else:
        posts = Post.objects.none()
        spaces = Space.objects.none()
        users = User.objects.none()

    context = {
        'q': q,
        'posts': posts,
        'spaces': spaces,
        'users': users
    }

    return render(request, 'search.html', context)


class UserInfoEdit(TemplateView):
    template_name = 'user/info-edit.html'


class UserProfile(TemplateView):
    template_name = 'user/profile.html'

    def get_object(self, queryset=None):
        slug = self.kwargs.get('slug')
        profile = get_object_or_404(Profile, slug=slug)
        user = profile.user
        message = None

        if profile.visibility == 'M' and profile.user != self.request.user:
            message = 'Профилът е скрит (само собственикът може да го види).'
        elif profile.visibility == 'F' and (not UserFollows.objects.filter(follower=self.request.user, following=profile.user).exists()) and profile.user != self.request.user:
            message = 'Само последователите и собственика могат да видят профила.'

        if message:
            return [user, message]

        return user

    def get_context_data(self, **kwargs):
        context = super(UserProfile, self).get_context_data(**kwargs)
        object_data = self.get_object()
        denied = False

        if isinstance(object_data, list):
            denied = True
            user = object_data[0]
            context['user'] = user
            context['denied_message'] = object_data[1]
        else:
            user = object_data
            context['user'] = user

        context['is_owner'] = (self.request.user == user)

        if UserFollows.objects.filter(follower=self.request.user, following=user).exists():
            context['followed'] = True
        else:
            context['followed'] = False

        context['followers_count'] = user.followers.count()
        context['following_count'] = user.following.count()

        if denied:
            return context

        if self.request.user == user:
            context['posts'] = Post.objects.filter(user=user).order_by('-created_at')
            context['saved_posts'] = user.saved_posts.all()
        else:
            context['posts'] = Post.objects.filter(user=user, visibility=True).order_by('-created_at')
            context['saved_posts'] = user.saved_posts.filter(post__visibility=True)
            context['is_reported'] = UserReport.objects.filter(reporter=self.request.user, reported_user=user).exists()

        context['comments'] = Comment.objects.filter(user=user, parent_comment__isnull=True).order_by('-created_at')
        context['replies'] = Comment.objects.filter(user=user, parent_comment__isnull=False).order_by('-created_at')
        context['liked_comments'] = user.comment_likes.all()

        context['spaces'] = Space.objects.filter(user=user).order_by('-created_at')
        context['followed_spaces'] = user.followed_spaces.all()

        context['display_choices'] = Profile.DISPLAY_CHOICES
        context['report_choices'] = UserReport.REPORT_TYPES
        return context


class UserFollowersAndFollowing(TemplateView):
    template_name = 'user/followers-following.html'

    def get_object(self):
        slug = self.kwargs.get('slug')
        profile = get_object_or_404(Profile, slug=slug)

        return profile.user

    def get_context_data(self, **kwargs):
        context = super(UserFollowersAndFollowing, self).get_context_data(**kwargs)
        user = self.get_object()

        context['user'] = user
        context['followers_list'] = user.followers.all()
        context['followings_list'] = user.following.all()

        return context

routing/templates/user/delete.html
{% extends "base.html" %}

{% block main %}
    <h1>Потвърди изтриване</h1>
    <p>Сигурни ли сте че искате да изтриете този акаунт? Това действие не може да бъде отменено.</p>
    <form method="POST">
        {% csrf_token %}
        {% include 'includes/errors.html' %}

        <div class="form-group mb-2">
            <label for="password">Въведете паролата си, за да потвърдите:</label>
            <input type="password" class="form-control" id="password" name="password" required>
        </div>
        <button type="submit" class="btn btn-danger mb-2">Изтрий акаунта ми</button>
    </form>
    <a href="{% url 'user_edit' %}" class="btn btn-secondary">Откажи</a>
{% endblock %}

routing/templates/user/followers-following.html
{% extends 'base.html' %}

{% block title %}{{ user.username }} Последователи и Последвани{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-lg-5">
            <div class="d-flex justify-content-center mb-2">
                <p><b>{{ user.username }}</b> го следват <b>{{ followers_list.count }}</b> потребителя</p>
            </div>
            {% for obj in followers_list %}
            <div class="card cursor-pointer on-hover-border" onclick="window.location.href='{% url 'user_profile' obj.follower.username %}'">
                <div class="card-body d-flex align-items-center gap-1">
                    <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#000000"><path d="M480-504.62q-49.5 0-84.75-35.25T360-624.62q0-49.5 35.25-84.75T480-744.62q49.5 0 84.75 35.25T600-624.62q0 49.5-35.25 84.75T480-504.62ZM200-215.38v-65.85q0-24.77 14.42-46.35 14.43-21.57 38.81-33.5 56.62-27.15 113.31-40.73 56.69-13.57 113.46-13.57 56.77 0 113.46 13.57 56.69 13.58 113.31 40.73 24.38 11.93 38.81 33.5Q760-306 760-281.23v65.85H200Zm40-40h480v-25.85q0-13.31-8.58-25-8.57-11.69-23.73-19.77-49.38-23.92-101.83-36.65-52.45-12.73-105.86-12.73t-105.86 12.73Q321.69-349.92 272.31-326q-15.16 8.08-23.73 19.77-8.58 11.69-8.58 25v25.85Zm240-289.24q33 0 56.5-23.5t23.5-56.5q0-33-23.5-56.5t-56.5-23.5q-33 0-56.5 23.5t-23.5 56.5q0 33 23.5 56.5t56.5 23.5Zm0-80Zm0 369.24Z"/></svg>
                    <h5 class="fw-light mb-0">{{ obj.follower.username }}</h5>
                    <small>&middot; {{ obj.follower.followers.count }} последователя</small>
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="col-lg-1 d-flex justify-content-center align-items-center">
            <div class="vr"></div>
        </div>

        <div class="col-lg-5">
            <div class="d-flex justify-content-center mb-2">
                <p><b>{{ user.username }}</b> следва <b>{{ followings_list.count }}</b> потребителя</p>
            </div>
            {% for obj in followings_list %}
            <div class="card cursor-pointer on-hover-border" onclick="window.location.href='{% url 'user_profile' obj.following.username %}'">
                <div class="card-body d-flex align-items-center gap-1">
                    <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#000000"><path d="M480-504.62q-49.5 0-84.75-35.25T360-624.62q0-49.5 35.25-84.75T480-744.62q49.5 0 84.75 35.25T600-624.62q0 49.5-35.25 84.75T480-504.62ZM200-215.38v-65.85q0-24.77 14.42-46.35 14.43-21.57 38.81-33.5 56.62-27.15 113.31-40.73 56.69-13.57 113.46-13.57 56.77 0 113.46 13.57 56.69 13.58 113.31 40.73 24.38 11.93 38.81 33.5Q760-306 760-281.23v65.85H200Zm40-40h480v-25.85q0-13.31-8.58-25-8.57-11.69-23.73-19.77-49.38-23.92-101.83-36.65-52.45-12.73-105.86-12.73t-105.86 12.73Q321.69-349.92 272.31-326q-15.16 8.08-23.73 19.77-8.58 11.69-8.58 25v25.85Zm240-289.24q33 0 56.5-23.5t23.5-56.5q0-33-23.5-56.5t-56.5-23.5q-33 0-56.5 23.5t-23.5 56.5q0 33 23.5 56.5t56.5 23.5Zm0-80Zm0 369.24Z"/></svg>
                    <h5 class="fw-light mb-0">{{ obj.following.username }}</h5>
                    <small>&middot; {{ obj.following.followers.count }} последователя</small>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

routing/templates/user/info-edit.html
{% extends 'base.html' %}

{% block title %}{{ user.username }} Редактирай профил{% endblock %}

{% block main %}
    <div id="app">
    <div class="card mb-5">
    <div class="card-body">
        <h3 class="card-title">Социални мрежи</h3>

        <label for="instagram-handle">Instagram</label>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">@</span>
            </div>
            <input v-model="instagramHandle" type="text" id="instagram-handle" class="form-control" placeholder="Потребителско име" aria-label="Username" aria-describedby="basic-addon1">
        </div>

        <label for="tiktok-handle">TikTok</label>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">@</span>
            </div>
            <input v-model="TikTokHandle" type="text" id="tiktok-handle" class="form-control" placeholder="Потребителско име" aria-label="Username" aria-describedby="basic-addon1">
        </div>

        <label for="x-handle">X</label>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">@</span>
            </div>
            <input v-model="xHandle" type="text" id="x-handle" class="form-control" placeholder="Потребителско име" aria-label="Username" aria-describedby="basic-addon1">
        </div>

        <label for="facebook-url">Facebook</label>
        <input v-model="facebookUrl" type="text" id="facebook-url" class="form-control" placeholder="Линк">
    </div>
    </div>

    <div class="card mb-3">
    <div class="card-body">
        <h3 class="card-title">Основна информация</h3>

        <label for="bio">Био</label>
        <textarea v-model="bio" class="form-control"></textarea>

        <label for="first_name">Име</label>
        <input v-model="firstName" type="text" id="first_name" class="form-control">

        <label for="last_name">Фамилия</label>
        <input v-model="lastName" type="text" id="last_name" class="form-control">

        <label for="birth_date">Рожденна дата</label>
        <input v-model="birthDate" type="date" id="birth_date" class="form-control">

        <label for="gender">Пол</label>
        <select v-model="gender" class="form-control" name="gender" id="gender">
            <option value="">Не избирам нищо</option>
            <option value="male">Мъж</option>
            <option value="female">Жена</option>
        </select>

        <label for="country">Държава</label>
        <input v-model="country" type="text" id="country" class="form-control">

        <label for="city">Град</label>
        <input v-model="city" type="text" id="city" class="form-control">
    </div>
    </div>

    <button class="btn btn-primary mb-5" @click="updateUserProfile">Запази</button>

    <div class="alert alert-danger" role="alert" id="danger-section">
        <h3 class="mb-3">Крайна информация</h3>
        <label for="username">Потребителско име</label>
        <input type="text" id="username" class="form-control" value="{{ user.username }}" disabled>

        <label for="email">Имейл адрес</label>
        <input type="text" id="email" class="form-control" value="{{ user.email }}" disabled>

        <label for="password">Парола</label>
        <input type="text" id="password" class="form-control" value="**********" disabled>

        <h5 class="mt-5">Смяна на парола</h5>
        <form action="{% url 'change_password' %}" method="POST">
            {% csrf_token %}
            {% include 'includes/errors.html' %}

            <label for="current_password">Текуща парола</label>
            <input type="password" id="current_password" class="form-control" name="old_password" required>

            <label for="new_password">Нова парола</label>
            <input type="password" id="new_password" class="form-control" name="new_password1" required>

            <label for="confirm_password">Повтори паролата</label>
            <input type="password" id="confirm_password" class="form-control" name="new_password2" required>

            <div class="mt-2 d-flex align-items-center gap-2">
                <button type="submit" class="btn btn-primary">Смени</button>
                <a href="{% url 'password_reset' %}" class="btn btn-primary">Забравена парола?</a>
            </div>
        </form>

        <a href="{% url 'delete_account' %}" class="btn btn-danger mt-3">Изтрий акаунт</a>
    </div>
    </div>

    {% include 'includes/message.html' %}
{% endblock %}

{% block rest %}
<script>
    axios.defaults.xsrfCookieName = 'csrftoken';
    axios.defaults.xsrfHeaderName = "X-CSRFTOKEN";

    {% include 'includes/js/vue-app-message.js' %}

    new Vue({
        delimiters: ['[[', ']]'],
        el: '#app',
        data: {
            instagramHandle: '{{ user.profile.instagram_handle|default_if_none:'' }}',
            TikTokHandle: '{{ user.profile.tiktok_handle|default_if_none:'' }}',
            xHandle: '{{ user.profile.x_handle|default_if_none:'' }}',
            facebookUrl: '{{ user.profile.facebook_url|default_if_none:'' }}',

            bio: '{{ user.profile.bio }}',
            firstName: '{{ user.first_name }}',
            lastName: '{{ user.last_name }}',
            birthDate: '{{ user.profile.birth_date|date:"Y-m-d" }}',
            gender: '{{ user.profile.gender|default_if_none:'' }}',
            country: '{{ user.profile.country|default_if_none:'' }}',
            city: '{{ user.profile.city|default_if_none:'' }}'
        },
        methods: {
            updateUserProfile() {
                const data = {
                    instagramHandle: this.instagramHandle,
                    TikTokHandle: this.TikTokHandle,
                    xHandle: this.xHandle,
                    facebookUrl: this.facebookUrl,
                    bio: this.bio,
                    firstName: this.firstName,
                    lastName: this.lastName,
                    birthDate: this.birthDate,
                    gender: this.gender,
                    country: this.country,
                    city: this.city
                };

                axios
                .put('{% url 'update_profile' %}', data)
                .then(response => {
                    messageApp.triggerNotification('Профилът беше подновен успешно');
                })
                .catch(error => {
                    messageApp.triggerNotification('Профилът не беше подновен успешно. Опитай по-късно.');
                });
            }
        },
        mounted() {
            {% if form.errors %}
            document.getElementById('danger-section').scrollIntoView();
            {% endif %}
        }
    });
</script>
<style>
    {% include 'includes/css/message.css' %}

    .input-group-text {
        border-radius: .25rem 0 0 .25rem;
    }
</style>
{% endblock %}

routing/templates/user/info.html
{% extends 'base.html' %}

{% block title %}{{ user.username }}'s info{% endblock %}

{% block main %}
    <div class="card mb-5">
    <div class="card-body">
        <h3 class="card-title">Social media</h3>

        <label for="instagram-handle">Instagram</label>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">@</span>
            </div>
            <input type="text" id="instagram-handle" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1"
                   {% if user.profile.instagram_handle %}disabled{% endif %} value="{{ user.profile.instagram_handle|default_if_none:'' }}">
        </div>

        <label for="tiktok-handle">TikTok</label>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">@</span>
            </div>
            <input type="text" id="tiktok-handle" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1"
            {% if user.profile.tiktok_handle %}disabled{% endif %} value="{{ user.profile.tiktok_handle|default_if_none:'' }}">
        </div>

        <label for="instagram-handle">X</label>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">@</span>
            </div>
            <input type="text" id="instagram-handle" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1"
            {% if user.profile.x_handle %}disabled{% endif %} value="{{ user.profile.x_handle|default_if_none:'' }}">
        </div>

        <label for="facebook-url">Facebook</label>
        <input type="text" id="facebook-url" class="form-control" placeholder="Link"
        {% if user.profile.facebook_url %}disabled{% endif %} value="{{ user.profile.facebook_url|default_if_none:'' }}">
    </div>
    </div>

    <div class="card mb-5">
    <div class="card-body">
        <h3 class="card-title">General</h3>

        <label for="bio">Bio</label>
        <textarea class="form-control" {% if user.profile.bio %}disabled{% endif %}>{{ user.profile.bio|default_if_none:'' }}</textarea>

        <label for="first_name">First Name</label>
        <input type="text" id="first_name" class="form-control" {% if user.first_name %}value="{{ user.first_name }}" disabled{% endif %}>

        <label for="last_name">Last Name</label>
        <input type="text" id="last_name" class="form-control" {% if user.last_name %}value="{{ user.last_name }}" disabled{% endif %}>

        <label for="birth_date">Birthdate</label>
        <input type="date" id="birth_date" class="form-control" {% if user.profile.birth_date %}value="{{ user.profile.birth_date|date:'Y-m-d' }}" disabled{% endif %}>

        <label for="gender">Gender</label>
        <select class="form-control" name="gender" id="gender" {% if user.profile.gender %}disabled{% endif %}>
            {% if not user.profile.gender %}<option value="none">Select gender</option>{% endif %}
            <option value="male" {% if user.profile.gender == 'male' %}selected{% endif %}>Male</option>
            <option value="female" {% if user.profile.gender == 'female' %}selected{% endif %}>Female</option>
            {% if user.profile.gender %}<option value="none">None</option>{% endif %}
        </select>

        <label for="country">Country</label>
        <input type="text" id="country" class="form-control" {% if user.profile.country %}value="{{ user.profile.country }}" disabled{% endif %}>

        <label for="city">City</label>
        <input type="text" id="city" class="form-control" {% if user.profile.city %}value="{{ user.profile.city }}" disabled{% endif %}>
    </div>
    </div>

    <div class="alert alert-danger" role="alert" id="danger-section">
        <h3 class="mb-3">Danger</h3>
        <label for="username">Username</label>
        <input type="text" id="username" class="form-control" value="{{ user.username }}" disabled>

        <label for="email">Email Address</label>
        <input type="text" id="email" class="form-control" value="{{ user.email }}" disabled>

        <label for="password">Password</label>
        <input type="text" id="password" class="form-control" value="**********" disabled>

        <h5 class="mt-5">Change password</h5>
        <label for="current_password">Current Password</label>
        <input type="password" id="current_password" class="form-control">

        <label for="new_password">New Password</label>
        <input type="password" id="new_password" class="form-control">

        <label for="confirm_password">Confirm Password</label>
        <input type="password" id="confirm_password" class="form-control">

        <button class="btn btn-danger mt-3">Delete Account</button>
    </div>
{% endblock %}

{% block rest %}
<script>

</script>
<style>
    .input-group-text {
        border-radius: .25rem 0 0 .25rem;
    }
</style>
{% endblock %}

routing/templates/user/notifications.html
{% extends 'base.html' %}

{% block title %}Нотификации на {{ user.username }}{% endblock %}

{% block main %}
    {% for notification in notifications %}
    <div class="card p-3 mb-2">
        <h1 class="fw-light">{{ notification.message }}</h1>
        {% if notification.notification_type == 'follow' %}
            <a href="{% url 'user_profile' notification.extra_data.user_slug %}" class="d-flex gap-1 align-items-end">
                <span>Виж профил:</span>
                <svg xmlns="http://www.w3.org/2000/svg" height="20px" viewBox="0 -960 960 960" width="20px" fill="#0d6efd"><path d="M480-504.62q-49.5 0-84.75-35.25T360-624.62q0-49.5 35.25-84.75T480-744.62q49.5 0 84.75 35.25T600-624.62q0 49.5-35.25 84.75T480-504.62ZM200-215.38v-65.85q0-24.77 14.42-46.35 14.43-21.57 38.81-33.5 56.62-27.15 113.31-40.73 56.69-13.57 113.46-13.57 56.77 0 113.46 13.57 56.69 13.58 113.31 40.73 24.38 11.93 38.81 33.5Q760-306 760-281.23v65.85H200Zm40-40h480v-25.85q0-13.31-8.58-25-8.57-11.69-23.73-19.77-49.38-23.92-101.83-36.65-52.45-12.73-105.86-12.73t-105.86 12.73Q321.69-349.92 272.31-326q-15.16 8.08-23.73 19.77-8.58 11.69-8.58 25v25.85Zm240-289.24q33 0 56.5-23.5t23.5-56.5q0-33-23.5-56.5t-56.5-23.5q-33 0-56.5 23.5t-23.5 56.5q0 33 23.5 56.5t56.5 23.5Zm0-80Zm0 369.24Z"/></svg>
                <span>{{ notification.extra_data.username }}</span>
            </a>
        {% elif notification.notification_type == 'reply' %}
            <a href="{% url 'post_details' notification.extra_data.post_slug %}?comment_link={{ notification.extra_data.comment_id }}" class="d-flex gap-1 align-items-end">
                <span>Виж коментарa</span>
            </a>
        {% elif notification.notification_type == 'post_created' %}
            <a href="{% url 'user_profile' user.profile.slug  %}#post_{{ notification.extra_data.post_id }}">Виж публикацията</a>
        {% elif notification.notification_type == 'space_created' %}
            <p>{{ notification.extra_data.space_name }}</p>
            <a href="{% url 'user_profile' user.profile.slug  %}#space_{{ notification.extra_data.space_id }}">Виж темата</a>
        {% elif notification.notification_type == 'space_deleted' %}
            <p>{{ notification.extra_data.space_name }}</p>
        {% endif %}
        <div class="d-flex gap-2 align-items-center">
            <span>{{ notification.get_notification_type_display }}</span>
            <span>|</span>
            <span>{{ notification.timestamp }}</span>
        </div>
    </div>
    {% endfor %}
{% endblock %}